package appl.databasemanagement;

public enum Searchfields {
	AUTHORID, NAMEF, NAMEL, 
	ISBN, TITLE, DESCRIPTION, PRICE, PUBLISHER, PUBDATE, EDITION, PAGES, 
	CATEGORYID, CATEGORYNAME, 
	SEARCHOR, SEARCHAND;
}
